### ISSUE TITLE
Write good tests for the module

### ISSUE THREAD

**Issue by icyflame** [icyflame/bar-horizontal#6]
After #5 is implemented, this should probably become better. (This would probably also need the option to pass terminal width as an argument, because travis terminal widths evaluate to 0, check [sample travis builds](https://travis-ci.org/icyflame/bar-horizontal/builds/297810567#L1060) )

**Comment by jrmykolyn** [comment]
Hey @icyflame 

Based on the contents of `index.js`, I would expect the module to test for the follow (see below). Let me know if there's anything I can help with!

- Ensure that module correctly exports a function (eg. module is 'require-able').
- Ensure that function correctly exits when invoked with a missing/invalid `inputObj`.
- Ensure that function can be invoked with 1x argument (eg. `inputObj`).
- Ensure that function can be invoked with 2x arguments (eg. `inputObj`, `options`).
- Ensure that 'labels' are NOT displayed by default.
- Ensure that 'labels' are displayed when `options` contains the `labels: true` key/value pair.
- Ensure that 'warnings' are NOT displayed by default.
- Ensure that 'warnings' are displayed when `options` contains the `warnings: true` key/value pair.
- Ensure that the bar graphs are composed of the `square` character by default.
- Ensure that the bar graphs are composed of the '=' character when options contains the `ascii: true` key/value pair.
